name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build Vite + React App
      run: npm run build

    - name: Archive Production Build
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build  # Change this to the actual build output directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: build
        path: build  # Change this to the actual build output directory

    # Add deployment steps as needed, such as deploying to a hosting service like Netlify, Vercel, or GitHub Pages.
    # For example, deploying to Netlify:
    # - name: Deploy to Netlify
    #   uses: nwtgck/actions-netlify@v1
    #   with:
    #     publish-dir: ./dist  # Change this to the actual build output directory
    #     production-command: ''

